apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: webapplication-container
        image: moizaman/webapplication:latest  # Replace with your Docker image
        ports:
        - containerPort: 5173  # Replace with the port your app runs on
