# k8s/deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
    spec:
      containers:
      - name: webapplication
        image: moizaman/webapplication:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webapplication

