apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: webapplication
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5173  # Replace with the port your app runs on
  selector:
    app: webapplication
